---

- name: Add Google Chrome key
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when: google_chrome_stable_enabled or google_talkplugin_enabled
  
- name: Add Google Chrome repo
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when: google_chrome_stable_enabled or google_talkplugin_enabled
  
- name: Install Google Chrome
  apt: pkg=google-chrome-stable state={{ google_agent_pkg_state }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when: google_chrome_stable_enabled

- name: Install Google Talk Plugin
  apt: pkg=google-talkplugin state={{ google_agent_pkg_state }}
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
  when: google_talkplugin_enabled
  
- name: Enable Yum repo for Google Chrome
  copy: dest=/etc/yum.repos.d/google-chrome.repo src=google-chrome.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  when: google_chrome_stable_enabled
  
- name: Install Google Chrome
  yum: name=google-chrome-stable state={{ google_agent_pkg_state }}
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  when: google_chrome_stable_enabled
  
- name: Enable Yum repo for Google Talk
  copy: dest=/etc/yum.repos.d/google-talkplugin.repo src=google-talkplugin.repo
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  when: google_talkplugin_enabled
  
- name: Install Google Talk Plugin
  yum: name=google-talkplugin state={{ google_agent_pkg_state }}
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  when: google_talkplugin_enabled
  
