---

- name: Remove duplicate entry.
  file: name=/etc/apt/sources.list.d/{{ item }} state=absent
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )
  with_items: "{{ google_repo_files }}"
  become: yes
  ignore_errors: yes

- name: Add Google Chrome key (apt)
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state={{ google_agent_repository_state|default('yes') }}
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( google_chrome_stable_enabled or google_talkplugin_enabled )
        and ((http_proxy is undefined) or (http_proxy is none))
  become: yes

- name: Add Google Chrome key (apt) (proxy)
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state={{ google_agent_repository_state|default('yes') }}
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( google_chrome_stable_enabled or google_talkplugin_enabled )
        and not( (http_proxy is undefined) or (http_proxy is none) )
        and (http_proxy | length > 0)
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  become: yes

- name: Add Google Chrome repo (apt)
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state={{ google_agent_repository_state|default('yes') }} update_cache=no
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ansible_architecture in ['x86_64'] and ( google_chrome_stable_enabled or google_talkplugin_enabled )
        and ((http_proxy is undefined) or (http_proxy is none))
  become: yes

- name: Add Google Chrome repo (apt) (proxy)
  apt_repository: repo="deb http://dl.google.com/linux/chrome/deb/ stable main" state={{ google_agent_repository_state|default('yes') }} update_cache=no
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ansible_architecture in ['x86_64'] and ( google_chrome_stable_enabled or google_talkplugin_enabled )
        and not( (http_proxy is undefined) or (http_proxy is none) )
        and (http_proxy | length > 0)
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
  become: yes

#Issue https://askubuntu.com/questions/724093/no-more-updates-for-google-chrome-apt-get-update-error
#TODO
#sudo sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/google-chrome.list" "/opt/google/chrome/cron/google-chrome"
- name: Fix Google drop support for 32 bits # noqa 303
  command: sed -i -e 's/deb http/deb [arch=amd64] http/' "/etc/apt/sources.list.d/dl_google_com_linux_chrome_deb.list"
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( google_chrome_stable_enabled or google_talkplugin_enabled )
  changed_when: false
  become: yes
  ignore_errors: yes

- name: Update the apt cache (in case of issue)
  action: apt update-cache=yes
  become: yes
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Install Google Chrome (apt)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ google_agent_pkg_state|default('present') }}"
  with_items:
    - google-chrome-stable
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and google_chrome_stable_enabled
  become: yes

- name: Add Google Talk repo (apt)
  apt_repository: repo="deb http://dl.google.com/linux/talkplugin/deb/ stable main" update_cache=yes state={{ google_agent_repository_state }}
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' )  and ( google_chrome_stable_enabled or google_talkplugin_enabled )
  become: yes
  tags:
    - talkplugin
    - vm

- name: Install Google Talk Plugin (apt)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ google_agent_pkg_state|default('present') }}"
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and google_talkplugin_enabled
  with_items:
   - google-talkplugin
  become: yes
  tags:
    - talkplugin
    - vm

- name: Install google-chrome-stable prerequisite
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ jenkins_pkg_state|default('present') }}"
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat')
  with_items:
    - libXScrnSaver
  become: yes
  changed_when: false

- name: Enable Yum repo for Google Chrome (yum)
  copy: dest=/etc/yum.repos.d/google-chrome.repo src=google-chrome.repo
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and google_chrome_stable_enabled
  become: yes

- name: Install Google Chrome (yum)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ google_agent_pkg_state|default('present') }}"
  with_items:
   - google-chrome-stable
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and google_chrome_stable_enabled
  become: yes

- name: Enable Yum repo for Google Talk (yum)
  copy: dest=/etc/yum.repos.d/google-talkplugin.repo src=google-talkplugin.repo
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and google_talkplugin_enabled
  become: yes
  tags:
    - talkplugin
    - vm

- name: Install Google Talk Plugin (yum)
  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ google_agent_pkg_state|default('present') }}"
  with_items:
   - google-talkplugin
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and google_talkplugin_enabled
  become: yes
  tags:
    - talkplugin
    - vm

#- name: Install Google remote desktop
#  action: "{{ ansible_pkg_mgr }} name={{ item }} state={{ google_agent_pkg_state|default('present') }}"
#  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and google_remotedesktop_enabled
#  with_items:
#   - chrome-remote-desktop
#  become: yes

- name: Install Google remote desktop (1)
  get_url:
    url: "{{ google_remotedesktop_url }}"
    dest: ./chrome-remote-desktop_current_amd64.deb
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and google_remotedesktop_enabled
  become: yes
  tags:
    - remotedesktop
    - vm

- name: Install Google remote desktop (2)
  command: apt install -y ./chrome-remote-desktop_current_amd64.deb
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and google_remotedesktop_enabled
  become: yes
  tags:
    - remotedesktop
    - vm

- name: Enable Google remote desktop
  debug: msg="Go to https://remotedesktop.google.com/access/"
  tags:
    - remotedesktop
    - vm
